# https://docs.openshift.com/container-platform/3.9/dev_guide/pod_autoscaling.html
# https://rancher.com/blog/2018/2018-08-06-k8s-hpa-resource-custom-metrics/
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ${SERVICE_NAME}-hpa
spec:
  minReplicas: 1 
  maxReplicas: 5 
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment 
    name: ${SERVICE_NAME}-worker
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90
  # - type: Resource
  #   resource:
  #     name: memory
  #     targetAverageValue: 100Mi
---
